# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven

name: Maven CI

on:
  release:
    types: [ created ]
  push:
    tags:
      - t*
      - v*

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.ARAGO_GPG_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish to Repository
        run: make deploy
        env:
          MVN_OPTIONS: "--batch-mode --no-transfer-progress -Dgpg.passphrase=${{ secrets.ARAGO_GPG_KEY_PASSWORD }}"
          GITHUB_TOKEN: ${{ secrets.ARAGO_GITHUB_TOKEN }}
